### ISSUE TITLE
Discussion: Why is a new contract instance created for each `.connect`?

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-ethers#1]
It is understood why we may need to change providers during contract calls or transactions, however, the `Contract.connect` func seems to create a new instance of a contract on every call:
https://github.com/status-im/nim-ethers/blob/27d6e8967268059f6071c56d4449b775ae1f0505/ethers/contract.nim#L28-L29

This style of immutable coding seems ok, as long as the caller understands that the contract instance is not the same instance that was originally created. Additionally, are we relying on the GC to collect all instances created by each call? What are the costs vs benefits for using this approach?

The [`nim-dagger-contracts` README](https://github.com/status-im/nim-dagger-contracts/blob/main/Readme.md) shows the following example, which would create three separate instances of the `storage` contract ref object:

```nim
let address = # fill in address where the contract was deployed
let storage = Storage.new(address, provider)

await storage
  .connect(host)
  .submitProof(id, blocknumber, proof)

await storage
  .connect(validator)
  .markProofAsMissing(id, blocknumber)

await storage
  .connect(host)
  .finishContract(id)
```

CC @michaelsbradleyjr

**Comment by markspanbroek** [comment]
Good question, thanks! Immutability is indeed one of the important properties of the ethers.js API, which is articulated for instance in the [documentation of the Signer](https://docs.ethers.io/v5/api/signer/#Signer--subclassing). Creating new instances indeed has a small cost involved; the garbage collector or resource counter has to free the memory. I think that in most cases this cost is negligible when we look at all that's involved in a contract interaction, but there may well be cases where this cost is unwanted. In those cases you can either store the result of the `connect` call in a variable, or call `Contract.new()` directly with a signer instead of a provider.

**Comment by emizzle** [comment]
Could we maybe introduce a `provider` setter (eg `setProvider`), such that a consumer could set the provider of the contract before executing methods? This may help retain a single instance, which could, for example, be useful for dependency injection and testing.

**Comment by markspanbroek** [comment]
> Could we maybe introduce a `provider` setter

I am not in favor of doing this because it would violate the immutability of the contract, which is a safety feature of this API. Bad things can happen when the provider is changed by one part of the code while another part of the code is performing contract calls.

**Comment by emizzle** [comment]
Makes sense, thanks Mark.
