### ISSUE TITLE
Allow calling global contracts functions inside logHandler

### ISSUE THREAD

**Issue by JackieWeiss** [status-im/nim-ethers#21]
given the following code
```nim
proc logHandler(log: Log) =
  echo waitFor Erc20.balanceOf(someaddress)

proc main() =
  let filter = Filter(address: Erc20.address, topics: @[])
  let subscription = provider.subscribe(filter, logHandler)
```
the balanceOf call inside the logHandler will never finish nor raise an exception. You can change logHandler to the following to make it work
```nim
proc logHandler(log: Log) =
  let local_provider = JsonRpcProvider.new(url)
  let local_erc = erc20_contract.new(someotheraddress, local_provider)
  echo waitFor local_erc.balanceOf(someaddress)
```
Allow it to use a globally defined contract instance to avoid the overhead of creating new instances

**Comment by markspanbroek** [comment]
I wouldn't recommend using `waitFor` in a callback, because it blocks execution of the callback until the call is completed. The `logHandler` callback in particular should do minimal work and return quickly, so that handling of JSON-RPC messages by the provider can resume.

If you need to kick off async logic from the callback, then you could do it as follows:

```nim
proc performAsyncLogic {.async.} =
  echo await Erc20.balanceOf(someaddress)

proc logHandler(log: Log) =
  asyncSpawn performAsyncLogic()
```

This is from the top of my head, I haven't compiled it :)
